
import { Language, Persona } from './types';

export const PERSONAS: Persona[] = [
  {
    name: 'VocalCoach',
    role: 'Primary Mentor',
    color: 'bg-[#1DB954]',
    avatar: 'https://picsum.photos/seed/vocalcoach/100/100'
  }
];

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'ar-MS', name: 'Arabic (MSA)', native: 'Al-Arabiyya al-Fusha' },
  { code: 'ar-EG', name: 'Arabic (Egyptian)', native: 'Al-Ammiya al-Misriyya' },
  { code: 'ar-LB', name: 'Arabic (Levantine)', native: 'Ash-Shami' },
  { code: 'ar-SA', name: 'Arabic (Gulf)', native: 'Al-Khaliji' },
  { code: 'ar-MA', name: 'Arabic (Maghrebi)', native: 'Ad-Darija al-Maghribiyya' },
  { code: 'ar-IQ', name: 'Arabic (Iraqi)', native: 'Al-Iraqi' },
  { code: 'ar-SD', name: 'Arabic (Sudanese)', native: 'As-Sudani' },
  { code: 'ar-YE', name: 'Arabic (Yemeni)', native: 'Al-Yamani' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands' },
  { code: 'sv', name: 'Swedish', native: 'Svenska' },
  { code: 'no', name: 'Norwegian', native: 'Norsk' },
  { code: 'da', name: 'Danish', native: 'Dansk' },
  { code: 'fi', name: 'Finnish', native: 'Suomi' },
  { code: 'is', name: 'Icelandic', native: 'Islenska' },
  { code: 'pl', name: 'Polish', native: 'Polski' },
  { code: 'cs', name: 'Czech', native: 'Cestina' },
  { code: 'sk', name: 'Slovak', native: 'Slovencina' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar' },
  { code: 'ro', name: 'Romanian', native: 'Romana' },
  { code: 'tr', name: 'Turkish', native: 'Turkce' },
  { code: 'el', name: 'Greek', native: 'Ellinika' },
  { code: 'ru', name: 'Russian', native: 'Russkiy' },
  { code: 'uk', name: 'Ukrainian', native: 'Ukrayinska' },
  { code: 'he', name: 'Hebrew', native: 'Ivrit' },
  { code: 'hi', name: 'Hindi', native: 'Hindi' },
  { code: 'bn', name: 'Bengali', native: 'Bangla' },
  { code: 'pa', name: 'Punjabi', native: 'Punjabi' },
  { code: 'te', name: 'Telugu', native: 'Telugu' },
  { code: 'mr', name: 'Marathi', native: 'Marathi' },
  { code: 'ta', name: 'Tamil', native: 'Tamil' },
  { code: 'gu', name: 'Gujarati', native: 'Gujarati' },
  { code: 'kn', name: 'Kannada', native: 'Kannada' },
  { code: 'ml', name: 'Malayalam', native: 'Malayalam' },
  { code: 'th', name: 'Thai', native: 'Thai' },
  { code: 'vi', name: 'Vietnamese', native: 'Tieng Viet' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu' },
  { code: 'tl', name: 'Tagalog', native: 'Tagalog' },
  { code: 'ja', name: 'Japanese', native: 'Nihongo' },
  { code: 'ko', name: 'Korean', native: 'Hangugo' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', native: 'Zhongwen' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', native: 'Guoyu' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili' },
  { code: 'af', name: 'Afrikaans', native: 'Afrikaans' },
  { code: 'zu', name: 'Zulu', native: 'isiZulu' },
  { code: 'xh', name: 'Xhosa', native: 'isiXhosa' },
  { code: 'yo', name: 'Yoruba', native: 'Yoruba' },
  { code: 'ig', name: 'Igbo', native: 'Igbo' },
  { code: 'am', name: 'Amharic', native: 'Amharic' },
  { code: 'so', name: 'Somali', native: 'Soomaali' },
  { code: 'ne', name: 'Nepali', native: 'Nepali' },
  { code: 'si', name: 'Sinhala', native: 'Sinhala' },
  { code: 'km', name: 'Khmer', native: 'Khmer' },
  { code: 'lo', name: 'Lao', native: 'Lao' },
  { code: 'my', name: 'Burmese', native: 'Bama' },
  { code: 'ka', name: 'Georgian', native: 'Kartuli' },
  { code: 'hy', name: 'Armenian', native: 'Hayeren' },
  { code: 'az', name: 'Azerbaijani', native: 'Azerbaycanca' },
  { code: 'uz', name: 'Uzbek', native: 'Oʻzbekcha' },
  { code: 'kk', name: 'Kazakh', native: 'Qazaqsha' },
  { code: 'et', name: 'Estonian', native: 'Eesti' },
  { code: 'lv', name: 'Latvian', native: 'Latviesu' },
  { code: 'lt', name: 'Lithuanian', native: 'Lietuviu' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski' },
  { code: 'sr', name: 'Serbian', native: 'Srpski' },
  { code: 'sq', name: 'Albanian', native: 'Shqip' },
  { code: 'mk', name: 'Macedonian', native: 'Makedonski' }
];

export const SCENARIOS = [
  { id: 'general', name: 'General Conversation', description: 'Friendly, intelligent peer interaction.' },
  { id: 'public', name: 'Public Speaking', description: 'High-stakes communications consulting.' },
  { id: 'leadership', name: 'Leadership & Crisis', description: 'High-pressure board room dilemmas.' }
];

export const GENERAL_TOPICS = [
  'Daily Routine & Habits',
  'Hobbies & Interests',
  'Travel & Vacation Stories',
  'Food & Culinary Adventures',
  'Movies & Cinema',
  'Music & Concerts',
  'Technology & Gadgets',
  'Future Plans & Dreams',
  'Childhood Memories',
  'Work-Life Balance',
  'Health & Wellness',
  'Sports & Fitness',
  'Shopping & Fashion',
  'Pets & Animals',
  'Nature & Environment',
  'Art & Creativity',
  'Cultural Traditions',
  'Books & Literature',
  'Global News & Trends',
  'Social Media & Communication',
  'Psychology & Mindset',
  'History & Landmarks',
  'Architecture & Design',
  'Education & Learning',
  'Space Exploration',
  'Cooking & Recipes',
  'Photography Tips',
  'Gaming & Esports',
  'Home Decor & DIY',
  'Philosophy of Life',
  'Astronomy',
  'Ocean Exploration',
  'Artificial Intelligence',
  'Sustainable Living',
  'Micro-adventures',
  'Urban Planning',
  'Ancient Civilizations',
  'Modern Art',
  'Classical Music',
  'Street Food Culture'
];

export const PUBLIC_SPEAKING_TOPICS = [
  'Pitching a Startup Idea',
  'Delivering a Keynote Speech',
  'Handling Q&A Sessions',
  'Motivational Storytelling',
  'Technical Sales Demo',
  'Wedding Toast Etiquette',
  'Debating Global Issues',
  'TED Talk Structure',
  'Persuasive Presentation',
  'Crisis Briefing',
  'Board Room Defense',
  'Rhetorical Devices Practice',
  'Body Language Mastery',
  'Overcoming Stage Fright',
  'Impacting Large Crowds',
  'Virtual Webinar Engagement',
  'Product Launch Reveal',
  'Scientific Findings Panel',
  'Influencing Stakeholders',
  'Political Campaign Rally'
];

export const LEADERSHIP_TOPICS = [
  'Resolving Team Conflict',
  'Managing Budget Cuts',
  'Ethical Dilemmas in Business',
  'Scaling Operations Rapidly',
  'Crisis Communication Strategy',
  'Product Recall Management',
  'Diversity & Inclusion Leadership',
  'Remote Team Management',
  'Performance Review Delivery',
  'Mergers & Acquisitions Panic',
  'Negotiating with Competitors',
  'Strategic Pivot Decision',
  'Company Culture Building',
  'Executive Succession Planning',
  'Risk Management Strategy',
  'Employee Morale Booster',
  'Sustainable Growth Policy',
  'Navigating PR Scandals',
  'Investor Relations Pressure',
  'Talent Acquisition Strategy'
];
